language: node_js
install: - cd ./blog-frontend
  - npm install
script: -npm run build
deploy:
  provider: netlify
  site: test
  dir: ./build
  cleanup: false
notifications:
  slack: code-soul:onWWUFlZgoIoYyB2mPcMo66e
